### ISSUE TITLE
Metadata validator failed with the REST end points.

### ISSUE THREAD

**Issue by keshavnangare** [opengeospatial/ets-19139#13]
Metadata validator failed with this REST end points on server and returned 500 Internal Server Error: 

http://cite-dev-03.opengeospatial.org/teamengine/rest/suites/iso19139/1.0/run?iut=http://cinergi.sdsc.edu/getmetadata/07FF6478-F2B9-4876-8CFB-E34A364B12F3.xml&sch=http://cinergi.sdsc.edu/proxyxslt/test-arg-ISOStyle.sch

Error log:

```
Error 
  ClientAbortException:  java.net.SocketException: Broken pipe
Jun 15, 2016 1:40:49 PM com.sun.jersey.server.impl.application.WebApplicationImpl _handleRequest
SEVERE: The response of the WebApplicationException cannot be utilized as the response is already committed. Re-throwing to the HTTP container
javax.ws.rs.WebApplicationException: net.sf.saxon.trans.XPathException: ClientAbortException:  java.net.SocketException: Broken pipe
    at com.sun.jersey.core.impl.provider.entity.SourceProvider$SourceWriter.writeTo(SourceProvider.java:214)
    at com.sun.jersey.core.impl.provider.entity.SourceProvider$SourceWriter.writeTo(SourceProvider.java:172)
    at com.sun.jersey.spi.container.ContainerResponse.write(ContainerResponse.java:302)
    at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1510)
    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
    at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
    at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:193)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:313)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: net.sf.saxon.trans.XPathException: ClientAbortException:  java.net.SocketException: Broken pipe
    at net.sf.saxon.event.XMLEmitter.characters(XMLEmitter.java:611)
    at net.sf.saxon.event.UncommittedSerializer.characters(UncommittedSerializer.java:62)
    at net.sf.saxon.event.ProxyReceiver.characters(ProxyReceiver.java:182)
    at net.sf.saxon.dom.DOMSender.walkNode(DOMSender.java:168)
    at net.sf.saxon.dom.DOMSender.outputElement(DOMSender.java:228)
    at net.sf.saxon.dom.DOMSender.walkNode(DOMSender.java:145)
    at net.sf.saxon.dom.DOMSender.outputElement(DOMSender.java:228)
    at net.sf.saxon.dom.DOMSender.walkNode(DOMSender.java:145)
    at net.sf.saxon.dom.DOMSender.outputElement(DOMSender.java:228)
    at net.sf.saxon.dom.DOMSender.walkNode(DOMSender.java:145)
    at net.sf.saxon.dom.DOMSender.outputElement(DOMSender.java:228)
    at net.sf.saxon.dom.DOMSender.walkNode(DOMSender.java:145)
    at net.sf.saxon.dom.DOMSender.outputElement(DOMSender.java:228)
    at net.sf.saxon.dom.DOMSender.walkNode(DOMSender.java:145)
    at net.sf.saxon.dom.DOMSender.outputElement(DOMSender.java:228)
    at net.sf.saxon.dom.DOMSender.walkNode(DOMSender.java:145)
    at net.sf.saxon.dom.DOMSender.outputElement(DOMSender.java:228)
    at net.sf.saxon.dom.DOMSender.walkNode(DOMSender.java:145)
    at net.sf.saxon.dom.DOMSender.outputElement(DOMSender.java:228)
    at net.sf.saxon.dom.DOMSender.walkNode(DOMSender.java:145)
    at net.sf.saxon.dom.DOMSender.send(DOMSender.java:97)
    at net.sf.saxon.dom.DOMObjectModel.sendSource(DOMObjectModel.java:112)
    at net.sf.saxon.event.Sender.send(Sender.java:218)
    at net.sf.saxon.IdentityTransformer.transform(IdentityTransformer.java:29)
    at com.sun.jersey.core.impl.provider.entity.SourceProvider$SourceWriter.writeTo(SourceProvider.java:208)
    ... 28 more
Caused by: ClientAbortException:  java.net.SocketException: Broken pipe
    at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:413)
    at org.apache.tomcat.util.buf.ByteChunk.flushBuffer(ByteChunk.java:480)
    at org.apache.tomcat.util.buf.ByteChunk.append(ByteChunk.java:366)
    at org.apache.catalina.connector.OutputBuffer.writeBytes(OutputBuffer.java:438)
    at org.apache.catalina.connector.OutputBuffer.write(OutputBuffer.java:426)
    at org.apache.catalina.connector.CoyoteOutputStream.write(CoyoteOutputStream.java:91)
    at com.sun.jersey.spi.container.servlet.WebComponent$Writer.write(WebComponent.java:300)
    at com.sun.jersey.spi.container.ContainerResponse$CommittingOutputStream.write(ContainerResponse.java:135)
    at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
    at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:282)
    at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125)
    at java.io.OutputStreamWriter.write(OutputStreamWriter.java:207)
    at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:129)
    at java.io.BufferedWriter.write(BufferedWriter.java:230)
    at java.io.Writer.write(Writer.java:157)
    at net.sf.saxon.event.XMLEmitter.writeCharSequence(XMLEmitter.java:622)
    at net.sf.saxon.event.XMLEmitter.writeEscape(XMLEmitter.java:715)
    at net.sf.saxon.event.XMLEmitter.characters(XMLEmitter.java:561)
    ... 52 more
Caused by: java.net.SocketException: Broken pipe
    at java.net.SocketOutputStream.socketWrite0(Native Method)
    at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
    at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
    at org.apache.coyote.ajp.AjpProcessor.output(AjpProcessor.java:295)
    at org.apache.coyote.ajp.AbstractAjpProcessor$SocketOutputBuffer.doWrite(AbstractAjpProcessor.java:1195)
    at org.apache.coyote.Response.doWrite(Response.java:520)
    at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:408)
    ... 69 more

Jun 15, 2016 1:40:49 PM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [TestSuiteController] in context with path [/teamengine] threw exception
java.lang.IllegalStateException: Cannot call sendError() after the response has been committed
    at org.apache.catalina.connector.ResponseFacade.sendError(ResponseFacade.java:450)
    at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:415)
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
    at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:193)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:313)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

```

**Comment by keshav-nangare** [comment]
Following URL is failing, when we trying to access and it returns the 500 internal server error.

http://cite-dev-03.opengeospatial.org/teamengine/rest/suites/iso19139/1.0/run?iut=http://cinergi.sdsc.edu/getmetadata/07FF6478-F2B9-4876-8CFB-E34A364B12F3.xml&sch=http://cinergi.sdsc.edu/proxyxslt/test-arg-ISOStyle.sch

The metadata validator is working with following URL:

1) http://54.209.245.204:8080/teamengine/rest/suites/iso19139/1.0/run?iut=http://cinergi.sdsc.edu/getmetadata/07FF6478-F2B9-4876-8CFB-E34A364B12F3.xml&sch=http://cinergi.sdsc.edu/proxyxslt/test-arg-ISOStyle.sch

2) When we execute this URL with curl command on AWS internally it is working as as expected:

`curl -sS 'http://localhost:8080/teamengine/rest/suites/iso19139/1.0/run?iut=http://cinergi.sdsc.edu/getmetadata/07FF6478-F2B9-4876-8CFB-E34A364B12F3.xml&sch=http://cinergi.sdsc.edu/proxyxslt/test-arg-ISOStyle.sch&ics=3'`

Maybe the issue with the server configuration, that's why it returns the 500 error.

We tried to execute other standards through the REST API that is working fine.

**Comment by bermud** [comment]
We are investigating why we are having this problem.

**Comment by ghobona** [comment]
This issue has been overtaken by events.
